# Change these first
owner: nexusguard # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
user-agent: nexusguard-status-probe

sites:
  - name: Nexusguard Public Website
    url: https://www.nexusguard.com
    method: GET

  - name: Nexusguard Mitigation Infrastructure
    url: https://www.nexusguard.com
    method: GET
    # "status":"up" for normal
    __dangerous__body_down: '"status":"down"'
    __dangerous__body_degraded: '"status":"degraded"'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.nexusguard.com
  baseUrl: /uptime
  logoUrl: https://assets-global.website-files.com/657ac0efa4c56f07f2a96a09/657ac0efa4c56f07f2a96a59_sticky-logo-1.svg
  favicon: https://assets-global.website-files.com/657ac0efa4c56f07f2a96a09/658682ffe0c14e285b4014fb_Nexusguard_Logo_Mark%201.png
  name: Nexusguard Status Page
  introTitle: "This is the status page of **Nexusguard** public-facing services"
  introMessage: Welcome to the status page of Nexusguard!
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: About Us
      href: https://nexusguard.com

workflowSchedule:
  graphs: "0 8 * * 1,3,5"
  responseTime: "0 8 * * 1,3,5"
  staticSite: "0 1 1 * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 1 * *"
  updates: "0 0 * * 1"
  # every 6 hours
  uptime: "0 */8 * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
